Add raw DVD reading with HL-DT-ST command
claunia/DiscImageChef pull request #823
Opened 2023-10-15 20:55 UTC by FakeShemp

You need an HL-DT-ST drive which support the HL-DT-ST SCSI command for this to work. Tested on a GDR-8163B.

Like all raw DVD reading commands, it is not activated yet, but the underlying functionality does work. I've managed to dump several DVDs with full prefix and suffix. CSS keys can be dumped this way and is magnitudes faster than the default way.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] New filesystem, test images in [url]
- [ ] New media image, test images in [url]
- [ ] New partition scheme, test images in [url]
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-15 22:03 UTC, claunia requested changes

2023-10-15 22:03 UTC, claunia commented on Aaru.Images/AaruFormat/Write.cs
> +                if(data.Length          == 2064 &&
What about DVD±R(W) and DVD-RAM?
What about PS3DVD, Nuon, and other DVD based storage (but NOD and WOD) media?

2023-10-15 23:04 UTC, FakeShemp commented on Aaru.Images/AaruFormat/Write.cs
> +                if(data.Length          == 2064 &&
I've added what I've tested, which was DVD Video and PS2DVD. I see no reason other pressed DVDs shouldn't work and can probably be added without issue. DVD-R might look fundamentally different in the cache, so we need to check first I think.

2023-10-15 23:06 UTC, claunia commented on Aaru.Images/AaruFormat/Write.cs
> +                if(data.Length          == 2064 &&
this is AaruFormat, it gets a 2064-byte formatted DVD sector, it doesn't care how it is in cache because that's, well, another part of the code (dumping), so this method should support all DVD based media (maybe even NOD/WOD) at this code point.

2023-10-16 19:37 UTC, claunia approved these changes

2023-10-16 19:38 UTC, merged